name: Examples 📕

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.6'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v1.5.2
        with:
          nim-version: ${{ matrix.nim_version }}

      - name: Install deps 👑
        run: |
          nimble refresh
          nimble install -y
      
      - name: Hello World 👋
        run: |
          cd examples/hello_world/src
          nim c -d:httpx main
          cd ../../../
        shell: bash
      
      - name: TODO App ✅
        run: |
          cd examples/todo/src
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
      
      - name: NimLang 👑
        run: |
          cd examples/nimlang/src
          nimble install highlightjs
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
      
      - name: Website 🌐
        run: |
          cd examples/website/src
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
