name: Examples 📕

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}
      
      - name: Install Dependencies
        run: |
          nimble refresh
          nimble install -y -d
      
      - name: Hello World 👋
        run: |
          cd examples/hello_world/src
          nim c -d:httpx main
          cd ../../../
        shell: bash
      
      - name: TODO App ✅
        run: |
          cd examples/todo/src
          nim js main
          cd ../../../
        shell: bash
      
      - name: NimLang 👑
        run: |
          cd examples/nimlang/src
          nim js main
          cd ../../../
        shell: bash
      
      - name: Website 🌐
        run: |
          cd examples/website/src
          nim js main
          cd ../../../
        shell: bash
