name: Examples 📕

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/tests.yml'
      - '**/language_bindings.yml'
      - '**/jvm_bindings.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.6'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v4

      - name: Install Nim 👑
        run: |
          sudo apt install xz-utils
          curl https://nim-lang.org/download/nim-${{ matrix.nim_version }}-linux_x64.tar.xz --output nim.tar.xz
          unxz nim.tar.xz
          tar -xf nim.tar
          sudo mkdir -p /home/.nimble
          sudo mv -if nim-${{ matrix.nim_version }}/* /home/.nimble/
          export PATH=/home/.nimble/bin:$PATH
          nim -v
          nimble refresh
          nimble install -y
      
      - name: Hello World 👋
        run: |
          export PATH=/home/.nimble/bin:$PATH
          cd examples/hello_world/src
          nim c -d:httpx main
          cd ../../../
        shell: bash
      
      - name: TODO App ✅
        run: |
          export PATH=/home/.nimble/bin:$PATH
          cd examples/todo/src
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
      
      - name: NimLang 👑
        run: |
          export PATH=/home/.nimble/bin:$PATH
          cd examples/nimlang/src
          nimble install highlightjs
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
      
      - name: Website 🌐
        run: |
          export PATH=/home/.nimble/bin:$PATH
          cd examples/website/src
          nim js --hints:off --warnings:off main
          cd ../../../
        shell: bash
