name: gh-pages

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'

permissions:
  contents: write

jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  docs:
    runs-on: ubuntu-latest
    needs: before
    env:
      nim_version: '1.6.12'
    steps:
      - uses: actions/checkout@v3

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim_version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          nimble refresh
          nimble install -y regex nimja cligen httpx microasynchttpserver illwill websocketx
          python -m pip install --upgrade pip
          pip install hapdoc>=1.9.25 -U

      - name: Build HapDoc Documentation
        run: |
          hapdoc -v
          hapdoc build docs -t default -o ""

      - name: Generate API documents
        run: nim doc --index:on -d:docgen --project --out:docs --hints:off src/happyx.nim

      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        if: github.ref == 'refs/heads/master'