name: Language Bindings 🐍

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/language_bindings.yml'
      - '**/bindings/**'
      - '**/constants.nim'
  pull_request:
    paths:
      - '**/language_bindings.yml'
      - '**/bindings/**'
      - '**/constants.nim'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
        python_version:
          - '3.x'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}

      - name: Set up Python 🔃
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
        
      - name: Install dependencies 🔃
        run: |
          nimble refresh
          nimble install -y -d
          python -m pip install --upgrade pip
          pip install -U twine build packaging jinja2
      
      - name: Python Bindings 🐍
        run: |
          cd src
          echo "Windows module"
          nim c --app:lib --out:../bindings/python/happyx/happyx.pyd --tlsEmulation:off --threads:on -d:debug -d:httpx -d:export2py happyx
          echo "Linux module"
          nim c --app:lib --out:../bindings/python/happyx/happyx.so --threads:on -d:debug -d:httpx -d:export2py happyx
        shell: bash

      - name: Publish Python package 📢
        run: |
          cd bindings/python/
          pip install -U twine build packaging jinja2
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
