name: Language Bindings ✨

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/language_bindings.yml'
      - '**/bindings/**'
      - '**/constants.nim'
  pull_request:
    paths:
      - '**/language_bindings.yml'
      - '**/bindings/**'
      - '**/constants.nim'

jobs:
  python:
    name: Python bindings 🐍
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - '3.x'
        nim_version:
          - '2.0.6'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v4

      - name: Install Nim 👑
        run: |
          sudo apt install xz-utils
          curl https://nim-lang.org/download/nim-${{ matrix.nim_version }}-linux_x64.tar.xz --output nim.tar.xz
          unxz nim.tar.xz
          tar -xf nim.tar
          sudo mkdir -p /home/.nimble
          sudo mv -if nim-${{ matrix.nim_version }}/* /home/.nimble/
          export PATH=/home/.nimble/bin:$PATH
          nim -v
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Python Dependencies 🐍
        run: |
          python -m pip install --upgrade pip
          pip install -U twine build packaging
      - name: Python Bindings 🐍
        run: |
          export PATH=/home/.nimble/bin:$PATH
          nimble refresh
          nimble install -y -d
          nimble install -y checksums nimpy
          sudo apt-get install gcc-aarch64-linux-gnu
          nimble list --installed
          cd src
          echo "Windows module"
          echo "Win Module compiled with"
          echo "nim c --app:lib --out:../bindings/python/happyx/happyx.pyd -d:useRealtimeGC --mm:arc --tlsEmulation:off --passL:-static --t:-flto --l:-flto --opt:speed --threads:off -d:release -d:httpx -d:export2py happyx"
          echo "Linux arm64"
          nim c --app:lib --out:../bindings/python/happyxpy/happyx_unix_amd64.so -d:useRealtimeGC --mm:arc -t:-flto -l:-flto --opt:speed --threads:off -d:release -d:happyxDebug -x:off -a:off -d:beast -d:export2py happyx
          echo "Linux arm64"
          nim c --app:lib --cpu:arm64 --out:../bindings/python/happyxpy/happyx_unix_arm64.so -d:useRealtimeGC --mm:arc -t:-flto -l:-flto --opt:speed --threads:off -d:release -d:happyxDebug -x:off -a:off -d:beast -d:export2py happyx
        shell: bash
      - name: Build Python Package 🏗
        run: |
          cd bindings/python
          python -m build
      # TODO:
      #   account recovery
      - name: Publish Python package 📢
        uses: pypa/gh-action-pypi-publish@8cdc2ab67c943c5edf5fd9ae1995546b4b550602
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: bindings/python/dist/
          verbose: true
  
  jvm:
    name: JVM Bindings ☕
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.6'
        java_version:
          - '16'
        gradle_version:
          - '7.4.2'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v4

      - name: Install Nim 👑
        run: |
          sudo apt install xz-utils
          curl https://nim-lang.org/download/nim-${{ matrix.nim_version }}-linux_x64.tar.xz --output nim.tar.xz
          unxz nim.tar.xz
          tar -xf nim.tar
          sudo mkdir -p /home/.nimble
          sudo mv -if nim-${{ matrix.nim_version }}/* /home/.nimble/
          export PATH=/home/.nimble/bin:$PATH
          nim -v

      - name: Install dependencies 🔃
        run: |
          export PATH=/home/.nimble/bin:$PATH
          nimble refresh
          nimble install -y -d
          nimble install -y jnim
          nimble install -y checksums
          nimble list --installed
          nim -v
      - uses: gradle/gradle-build-action@v3
        id: setup-gradle
        with:
          gradle-version: ${{ matrix.gradle_version }}
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'
      - name: JVM Bindings ☕
        run: |
          export PATH=/home/.nimble/bin:$PATH
          cd src
          echo "Unix module"
          nim c -d:noSignalHandler -d:export2jvm -d:release -d:httpx --app:lib --threads:on --opt:speed --mm:arc --out:../bindings/java/src/main/resources/happyx.so happyx.nim
          cd ..
      - name: Build Java Project ☕
        run: |
          cd bindings/java
          gradle build --scan
