name: Testing

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - 'stable'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}
      
      - name: Install Dependencies
        run: |
          nimble refresh
          nimble install -y
      
      - name: Build C tests
        run: |
          cd tests
          for file in $(ls -v testc*.nim); do
            nim c -d:debug $file
            nim c -d:httpx -d:debug $file
          done
        shell: bash
      
      - name: Build JS tests
        run: |
          cd tests
          for file in $(ls -v testjs*.nim); do
            nim js -d:debug -d:enableUi $file
          done
        shell: bash
