name: Testing 👨‍🔬

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/examples.yml'
      - '**/language_bindings.yml'
      - '**/examples/website/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/*'
      - '*.md'
      - '*.nimble'
      - '.gitignore'
      - 'LICENSE'
      - '**/FUNDING.yml'
      - '**/gh-pages.yml'
      - '**/examples.yml'
      - '**/language_bindings.yml'
      - '**/examples/website/**'

jobs:
  dependencies:
    name: Install dependencies 🧩
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Install Dependencies 🔃
        run: |
          nimble refresh
          nimble install -y -d
  async_http_server:
    name: Test C via AsyncHttpServer 🧪
    needs: dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Restore nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Restore Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH
      - name: Build C tests (Default HTTP Server) ⚡
        run: |
          cd tests
          echo "###===--- Default for" $file "---===###"
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via stdlib ---===###"
            nim c -d:debug --hints:off --warnings:off $file
          done
        shell: bash
  micro_async_http_server:
    name: Test C via MicroAsyncHttpServer 🧪
    needs: dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Restore nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Restore Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH
      - name: Build C tests (MicroAsyncHttpServer) ⚡
        run: |
          cd tests
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via MicroAsyncHttpServer ---===###"
            nim c -d:micro -d:debug --hints:off --warnings:off $file
          done
        shell: bash
  httpx:
    name: Test C via HttpX 🧪
    needs: dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Restore nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Restore Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH
      - name: Build C tests (HttpX HTTP Server) ⚡
        run: |
          cd tests
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via Httpx ---===###"
            nim c -d:httpx -d:debug --hints:off --warnings:off $file
          done
        shell: bash
  httpbeast:
    name: Test C via HttpBeast 🧪
    needs: dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Restore nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Restore Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH
      - name: Build C tests (HttpBeast HTTP Server) ⚡
        run: |
          cd tests
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via HttpBeast ---===###"
            nim c -d:beast -d:debug --hints:off --warnings:off $file
          done
        shell: bash
  js:
    name: Test with JavaScript 🧪
    needs: dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim_version:
          - '2.0.0'
    env:
      TIMEOUT_EXIT_STATUS: 124
    steps:
      - uses: actions/checkout@v3
      - name: Restore nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - name: Restore Nim
        run: export PATH=/home/runner/.nimble/bin:$PATH
      - name: Build JS tests 🍍
        run: |
          cd tests
          for file in $(ls -v testjs*.nim); do
            echo "###===--- JS Test for " $file " ---===###"
            nim js -d:debug --hints:off --warnings:off $file
          done
        shell: bash
